[2024-11-21T13:41:15.762+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T13:41:15.797+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: candlestick_analysis.carregar_arquivo manual__2024-11-21T13:33:10.088686+00:00 [queued]>
[2024-11-21T13:41:15.816+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: candlestick_analysis.carregar_arquivo manual__2024-11-21T13:33:10.088686+00:00 [queued]>
[2024-11-21T13:41:15.817+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-21T13:41:15.843+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): carregar_arquivo> on 2024-11-21 13:33:10.088686+00:00
[2024-11-21T13:41:15.866+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=103) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-21T13:41:15.869+0000] {standard_task_runner.py:72} INFO - Started process 119 to run task
[2024-11-21T13:41:15.869+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'candlestick_analysis', 'carregar_arquivo', 'manual__2024-11-21T13:33:10.088686+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/application.py', '--cfg-path', '/tmp/tmpdrhngb48']
[2024-11-21T13:41:15.873+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask carregar_arquivo
[2024-11-21T13:41:15.969+0000] {task_command.py:467} INFO - Running <TaskInstance: candlestick_analysis.carregar_arquivo manual__2024-11-21T13:33:10.088686+00:00 [running]> on host fb24f94975fd
[2024-11-21T13:41:16.139+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='candlestick_analysis' AIRFLOW_CTX_TASK_ID='carregar_arquivo' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T13:33:10.088686+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T13:33:10.088686+00:00'
[2024-11-21T13:41:16.142+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-21T13:41:16.143+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-21T13:41:16.145+0000] {logging_mixin.py:190} INFO - Current task name:carregar_arquivo state:running start_date:2024-11-21 13:41:15.799385+00:00
[2024-11-21T13:41:16.146+0000] {logging_mixin.py:190} INFO - Dag name:candlestick_analysis and current dag run status:running
[2024-11-21T13:41:16.147+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T13:41:16.180+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/_optional.py", line 132, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/application.py", line 14, in carregar_arquivo
    df = pd.read_excel(file_path, sheet_name="NFLX")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1580, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/application.py", line 18, in carregar_arquivo
    raise ValueError(f"Erro ao carregar arquivo: {e}")
ValueError: Erro ao carregar arquivo: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2024-11-21T13:41:16.223+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-21T13:41:16.224+0000] {logging_mixin.py:190} INFO - Task start:2024-11-21 13:41:15.799385+00:00 end:2024-11-21 13:41:16.222518+00:00 duration:0.423133
[2024-11-21T13:41:16.226+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): carregar_arquivo> dag:<DAG: candlestick_analysis> dagrun:<DagRun candlestick_analysis @ 2024-11-21 13:33:10.088686+00:00: manual__2024-11-21T13:33:10.088686+00:00, state:running, queued_at: 2024-11-21 13:33:10.132841+00:00. externally triggered: True>
[2024-11-21T13:41:16.227+0000] {logging_mixin.py:190} INFO - Failure caused by Erro ao carregar arquivo: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2024-11-21T13:41:16.229+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=candlestick_analysis, task_id=carregar_arquivo, run_id=manual__2024-11-21T13:33:10.088686+00:00, execution_date=20241121T133310, start_date=20241121T134115, end_date=20241121T134116
[2024-11-21T13:41:16.260+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T13:41:16.261+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task carregar_arquivo (Erro ao carregar arquivo: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 119)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/_optional.py", line 132, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/application.py", line 14, in carregar_arquivo
    df = pd.read_excel(file_path, sheet_name="NFLX")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1580, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/application.py", line 18, in carregar_arquivo
    raise ValueError(f"Erro ao carregar arquivo: {e}")
ValueError: Erro ao carregar arquivo: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2024-11-21T13:41:16.334+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-21T13:41:16.384+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-21T13:41:16.393+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
