[2024-11-21T15:32:17.622+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T15:32:17.662+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: candlestick_analysis.plot_clusters manual__2024-11-21T15:30:26.803509+00:00 [queued]>
[2024-11-21T15:32:17.681+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: candlestick_analysis.plot_clusters manual__2024-11-21T15:30:26.803509+00:00 [queued]>
[2024-11-21T15:32:17.683+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-21T15:32:17.708+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): plot_clusters> on 2024-11-21 15:30:26.803509+00:00
[2024-11-21T15:32:17.731+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=560) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-21T15:32:17.736+0000] {standard_task_runner.py:72} INFO - Started process 569 to run task
[2024-11-21T15:32:17.733+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'candlestick_analysis', 'plot_clusters', 'manual__2024-11-21T15:30:26.803509+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/application.py', '--cfg-path', '/tmp/tmpmthebr3p']
[2024-11-21T15:32:17.738+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask plot_clusters
[2024-11-21T15:32:17.842+0000] {task_command.py:467} INFO - Running <TaskInstance: candlestick_analysis.plot_clusters manual__2024-11-21T15:30:26.803509+00:00 [running]> on host c397a827dfef
[2024-11-21T15:32:18.019+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='candlestick_analysis' AIRFLOW_CTX_TASK_ID='plot_clusters' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T15:30:26.803509+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T15:30:26.803509+00:00'
[2024-11-21T15:32:18.022+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-21T15:32:18.024+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-21T15:32:18.025+0000] {logging_mixin.py:190} INFO - Current task name:plot_clusters state:running start_date:2024-11-21 15:32:17.663299+00:00
[2024-11-21T15:32:18.026+0000] {logging_mixin.py:190} INFO - Dag name:candlestick_analysis and current dag run status:running
[2024-11-21T15:32:18.027+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T15:32:18.466+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/application.py", line 136, in plot_clusters
    fig.write_html("/opt/airflow/output/candlestick_chart.html")
  File "/home/airflow/.local/lib/python3.12/site-packages/plotly/basedatatypes.py", line 3714, in write_html
    return pio.write_html(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/plotly/io/_html.py", line 535, in write_html
    path.write_text(html_str, "utf-8")
  File "/usr/local/lib/python3.12/pathlib.py", line 1047, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output/candlestick_chart.html'
[2024-11-21T15:32:18.491+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-21T15:32:18.492+0000] {logging_mixin.py:190} INFO - Task start:2024-11-21 15:32:17.663299+00:00 end:2024-11-21 15:32:18.491421+00:00 duration:0.828122
[2024-11-21T15:32:18.494+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): plot_clusters> dag:<DAG: candlestick_analysis> dagrun:<DagRun candlestick_analysis @ 2024-11-21 15:30:26.803509+00:00: manual__2024-11-21T15:30:26.803509+00:00, state:running, queued_at: 2024-11-21 15:30:26.872036+00:00. externally triggered: True>
[2024-11-21T15:32:18.495+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/opt/***/output/candlestick_chart.html'
[2024-11-21T15:32:18.496+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=candlestick_analysis, task_id=plot_clusters, run_id=manual__2024-11-21T15:30:26.803509+00:00, execution_date=20241121T153026, start_date=20241121T153217, end_date=20241121T153218
[2024-11-21T15:32:18.515+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T15:32:18.516+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 58 for task plot_clusters ([Errno 2] No such file or directory: '/opt/airflow/output/candlestick_chart.html'; 569)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/application.py", line 136, in plot_clusters
    fig.write_html("/opt/airflow/output/candlestick_chart.html")
  File "/home/airflow/.local/lib/python3.12/site-packages/plotly/basedatatypes.py", line 3714, in write_html
    return pio.write_html(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/plotly/io/_html.py", line 535, in write_html
    path.write_text(html_str, "utf-8")
  File "/usr/local/lib/python3.12/pathlib.py", line 1047, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output/candlestick_chart.html'
[2024-11-21T15:32:18.560+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-21T15:32:18.584+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-21T15:32:18.587+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
